### ISSUE TITLE
Guide for x86_64 is out of date? 

### ISSUE THREAD

**Issue by aprentis** [yankailab/OpenKAI#12] opened 2017-07-12 10:47 UTC
Ubuntu 16.04

I`ve tried to follow this guide: http://www.openkai.xyz/x86build.html and got errors while compiling jetson-inference. 
jetson-inference/tensorNet.h:159:12: error: ‘Dims3’ in namespace ‘nvinfer1’ does not name a type

I`ve tried it with TensorRT 2.1 and 1.0 both. 
Also i`ve tried to build OpenKAI and got this: tensorRT.h:3:30: fatal error: cudaMappedMemory.h: No such file or directory. 

What`s wrong with this guide?

**Comment by yankailab** [comment] 2017-07-13 05:11
Hi Aprentis, looks like the dir to dependencies are not set correctly.
Could you try ccmake to set up directories:


`cd ~/src/jetson-inference/`
`mkdir build`
`cd build`
`ccmake ../             //<-Use ccmake instead of cmake, will open the configuration for cmake, set the directories according to your own environment, then press "c" multiple times and "g".`
`make`

Btw, currently it only support TensorRT 1.0. TensorRT 2.0 support is in my task list.

**Comment by aprentis** [comment] 2017-07-13 07:26
Hi @yankailab, Thank you for your reply! 

On the screenshots mentioned in tutorial there`re plenty of variables. Is it necessary to fill them all, or just several "important" ones?

**Comment by aprentis** [comment] 2017-07-13 11:45
@yankailab 
After i`ve run ccmake manually, i`ve got this. 
![screenshot from 2017-07-13 14-30-35](https://user-images.githubusercontent.com/17255184/28164403-f97eefa6-67d7-11e7-97b6-919cb513f7d6.png)

Then i`ve run make. And nothing changed.

![screenshot from 2017-07-13 14-33-34](https://user-images.githubusercontent.com/17255184/28164503-57eeeec4-67d8-11e7-811d-52e03a5716e4.png)

i`ve tried to change CUDA_SDK_ROOT_DIR to /usr/local/cuda but there also was no success. 
What`s wrong with it now? 

![screenshot from 2017-07-13 14-44-34](https://user-images.githubusercontent.com/17255184/28164837-e55a4cbc-67d9-11e7-8cb7-2e0825ed5ec6.png)

**Comment by yankailab** [comment] 2017-07-13 11:57
@aprentis , sorry it was my mistake, you dont have to do ccmake for jetson-inference, just cmake and make jetson-inference following its official guide and it should be fine if successfully built.

The problem is for OpenKAI, when ccmake for OpenKAI, have you set all the dir correctly acording to your environment? Cuda root etc. should be okay as they are found and set automatically, pay attention to TensorRT_include and TensorRT_lib as the two should be set manually according to your environment.

![ccmake for OpenKAI](http://www.openkai.xyz/images/OpenKAI_ccmake.png)

**Comment by aprentis** [comment] 2017-07-13 13:10
@yankailab Ok, Thank you! 

But jetson-inference does not build successfully on my x86_64, as i`ve mentioned above.

**Comment by cudnn** [comment] 2017-08-03 15:01
Hi  @yankailab may i  only use i5 i7 cpu run openkai,dot not use nv card

**Comment by cudnn** [comment] 2017-08-03 15:02
Hi @yankailab may i only use  stero usb camera  instade zed rgbd camera

**Comment by yankailab** [comment] 2017-09-04 06:27
@aprentis I updated the install process, please refer here:
http://www.openkai.xyz/x86build.html

**Comment by yankailab** [comment] 2017-09-04 06:28
@cudnn at the moment I only tested with nvidia GPU installed, will add more support for non-nv setup in future. What kind of usb stereo camera are you going to use?

**Comment by aprentis** [comment] 2017-09-13 15:55
@yankailab thank you for the manual. I've managed to pass recent errors, but now I have another problem. While compiling openKAI with Orb_Slam2_gpu my computer got stuck. It's absolutely frozen, even mouse does not move. I've repeated this situation and got the same result. Maybe I should disable ORB_Slam2? 


![img_0637](https://user-images.githubusercontent.com/17255184/30387391-fab2dc94-98b4-11e7-9fb7-924d8ab79597.JPG)

**Comment by yankailab** [comment] 2017-09-14 07:39
@aprentis , hello, I never met such frozen, which version of gcc are you using?
May not be the cause but could you try to remove -j option of make in build.sh?

**Comment by aprentis** [comment] 2017-09-14 08:32
@yankailab yesterday I decided to leave my computer for some time and got this error. 
Today I'll try to build without -j option.  
![img_0638](https://user-images.githubusercontent.com/17255184/30419833-6abd0fb0-9940-11e7-9b69-f5bb8bd7b096.JPG)

**Comment by yankailab** [comment] 2018-04-17 07:10
Working on the documentation site for Kiss files, will be released on
docs.openkai.xyz
(hopefully) soon

**Closed by yankailab** 2018-04-17 07:10 UTC
